[package]
name = "merkle"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "poseidon"]

[dependencies]
anyhow = "1.0.75"
zkhash = { path = "./poseidon" }
ark-ff = { version = "^0.4.0", default-features = false }
serde = "1.0"
